using FlatBufferLite.SourceGen.IR;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace FlatBufferLite.SourceGen.Emit;

public sealed class CodeEmitter
{
	readonly Schema _schema;
	readonly StringBuilder _sb = new();
	readonly HashSet<string> _refUnions = new();

	public CodeEmitter(Schema schema) { _schema = schema; }

	public string Emit()
	{
		_sb.Clear();
		_sb.AppendLine("// <auto-generated/> FlatBufferLite source generator");
		_sb.AppendLine("#nullable enable");
		_sb.AppendLine("using System;");
		_sb.AppendLine("using System.Runtime.CompilerServices;");
		_sb.AppendLine("using System.Runtime.InteropServices;");
		_sb.AppendLine("using FlatBufferLite;");

		var referencedNamespaces = new HashSet<string?>();
		foreach (var t in _schema.Tables)
			referencedNamespaces.Add(t.Namespace);
		foreach (var s in _schema.Structs)
			referencedNamespaces.Add(s.Namespace);
		foreach (var e in _schema.Enums)
			referencedNamespaces.Add(e.Namespace);
		foreach (var u in _schema.Unions)
			referencedNamespaces.Add(u.Namespace);
		foreach (var ns in referencedNamespaces)
			if (!string.IsNullOrEmpty(ns))
				_sb.Append("using ").Append(ns).AppendLine(";");

		int enumCount = _schema.LocalEnumCount;
		int structCount = _schema.LocalStructCount;
		int unionCount = _schema.LocalUnionCount;
		int tableCount = _schema.LocalTableCount;

		for (int i = 0; i < unionCount; i++)
			PreclassifyUnion(_schema.Unions[i]);

		var namespaces = new List<string?>();
		var nsSeen = new HashSet<string?>();
		void Track(string? ns)
		{
			if (nsSeen.Add(ns))
				namespaces.Add(ns);
		}
		for (int i = 0; i < enumCount; i++)
			Track(_schema.Enums[i].Namespace);
		for (int i = 0; i < structCount; i++)
			Track(_schema.Structs[i].Namespace);
		for (int i = 0; i < unionCount; i++)
			Track(_schema.Unions[i].Namespace);
		for (int i = 0; i < tableCount; i++)
			Track(_schema.Tables[i].Namespace);

		foreach (var ns in namespaces)
		{
			bool hasNs = !string.IsNullOrEmpty(ns);
			if (hasNs)
			{
				_sb.AppendLine();
				_sb.Append("namespace ").AppendLine(ns);
				_sb.AppendLine("{");
			}
			for (int i = 0; i < enumCount; i++)
				if (_schema.Enums[i].Namespace == ns)
					EmitEnum(_schema.Enums[i]);
			for (int i = 0; i < structCount; i++)
				if (_schema.Structs[i].Namespace == ns)
					EmitStruct(_schema.Structs[i]);
			for (int i = 0; i < unionCount; i++)
				if (_schema.Unions[i].Namespace == ns)
					EmitUnion(_schema.Unions[i]);
			for (int i = 0; i < tableCount; i++)
				if (_schema.Tables[i].Namespace == ns)
					EmitTable(_schema.Tables[i]);
			if (hasNs)
				_sb.AppendLine("}");
		}
		return _sb.ToString();
	}

	void PreclassifyUnion(UnionDef u)
	{
		if (u.Members.Count == 0)
		{
			_refUnions.Add(u.Name);
			return;
		}
		foreach (var m in u.Members)
		{
			bool isManaged = _schema.ByName.TryGetValue(m.TypeName, out var def)
				&& (def is StructDef || def is EnumDef);
			if (!isManaged)
			{
				_refUnions.Add(u.Name);
				return;
			}
		}
	}

	void EmitEnum(EnumDef e)
	{
		_sb.AppendLine();
		if (e.IsBitFlags)
			_sb.AppendLine("[System.Flags]");
		_sb.Append("public enum ").Append(e.Name).Append(" : ").AppendLine(e.Underlying.ToCSharpKeyword());
		_sb.AppendLine("{");
		foreach (var v in e.Values)
		{
			long emitValue = e.IsBitFlags
				? (v.IsExplicit && v.Value == 0 ? 0 : 1L << (int)v.Value)
				: v.Value;
			_sb.Append('\t').Append(v.Name).Append(" = ").Append(emitValue.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
		}
		_sb.AppendLine("}");
	}

	void EmitStruct(StructDef s)
	{
		_sb.AppendLine();
		_sb.Append("[StructLayout(LayoutKind.Explicit, Size = ").Append(s.Size).AppendLine(")]");
		_sb.Append("public partial struct ").AppendLine(s.Name);
		_sb.AppendLine("{");
		foreach (var f in s.Fields)
		{
			string cs = ResolveTypeName(f.Type);
			_sb.Append("\t[FieldOffset(").Append(f.Offset).AppendLine(")]");
			_sb.Append("\tpublic ").Append(cs).Append(' ').Append(ToPascalCase(f.Name)).AppendLine(";");
		}
		_sb.AppendLine("}");
	}

	void EmitUnion(UnionDef u)
	{
		_sb.AppendLine();
		_sb.Append("public enum ").Append(u.Name).AppendLine("Kind : byte");
		_sb.AppendLine("{");
		_sb.AppendLine("\tNONE = 0,");
		foreach (var m in u.Members)
			_sb.Append('\t').Append(m.Name).Append(" = ").Append(m.Tag).AppendLine(",");
		_sb.AppendLine("}");

		bool allUnmanaged = u.Members.Count > 0;
		bool allTables = u.Members.Count > 0;
		int maxSize = 0;
		int maxAlign = 1;
		foreach (var m in u.Members)
		{
			if (_schema.ByName.TryGetValue(m.TypeName, out var def))
			{
				if (def is StructDef sd)
				{
					allTables = false;
					if (sd.Size > maxSize)
						maxSize = sd.Size;
					if (sd.Alignment > maxAlign)
						maxAlign = sd.Alignment;
				}
				else if (def is TableDef)
				{
					allUnmanaged = false;
				}
				else if (def is EnumDef ed)
				{
					allTables = false;
					int sz = ed.Underlying.InlineSize();
					if (sz > maxSize)
						maxSize = sz;
					if (sz > maxAlign)
						maxAlign = sz;
				}
				else
				{
					allUnmanaged = false;
					allTables = false;
				}
			}
			else
			{
				allUnmanaged = false;
			}
		}

		if (allUnmanaged)
			EmitContiguousUnion(u, maxSize, maxAlign);
		else
		{
			_refUnions.Add(u.Name);
			EmitRefUnion(u, allTables);
		}
	}

	void EmitContiguousUnion(UnionDef u, int maxSize, int maxAlign)
	{
		int tagOffset = maxSize;
		int totalSize = AlignUp(tagOffset + 1, maxAlign > 0 ? maxAlign : 1);

		_sb.AppendLine();
		_sb.AppendLine("[Union]");
		_sb.Append("[StructLayout(LayoutKind.Explicit, Size = ").Append(totalSize).AppendLine(")]");
		_sb.Append("public struct ").Append(u.Name).AppendLine(" : IUnion");
		_sb.AppendLine("{");
		_sb.Append("\t[FieldOffset(").Append(tagOffset).AppendLine(")] public byte Tag;");
		foreach (var m in u.Members)
			_sb.Append("\t[FieldOffset(0)] public ").Append(m.TypeName).Append(' ').Append(m.Name).AppendLine(";");
		_sb.AppendLine();
		_sb.AppendLine("\tpublic object? Value => throw new NotImplementedException(\"Boxing not supported. Use TryGetValue.\");");
		_sb.AppendLine("\tpublic readonly bool HasValue => Tag != 0;");
		foreach (var m in u.Members)
		{
			_sb.AppendLine();
			_sb.Append("\tpublic ").Append(u.Name).Append('(').Append(m.TypeName).AppendLine(" value)");
			_sb.AppendLine("\t{");
			_sb.Append("\t\tvar u = default(").Append(u.Name).AppendLine(");");
			_sb.Append("\t\tu.").Append(m.Name).AppendLine(" = value;");
			_sb.Append("\t\tu.Tag = ").Append(m.Tag).AppendLine(";");
			_sb.AppendLine("\t\tthis = u;");
			_sb.AppendLine("\t}");

			_sb.AppendLine();
			_sb.Append("\tpublic static ").Append(u.Name).Append(" From").Append(m.Name).Append('(').Append(m.TypeName).AppendLine(" value)");
			_sb.AppendLine("\t{");
			_sb.Append("\t\tvar u = default(").Append(u.Name).AppendLine(");");
			_sb.Append("\t\tu.").Append(m.Name).AppendLine(" = value;");
			_sb.Append("\t\tu.Tag = ").Append(m.Tag).AppendLine(";");
			_sb.AppendLine("\t\treturn u;");
			_sb.AppendLine("\t}");

			_sb.AppendLine();
			_sb.Append("\tpublic readonly bool TryGetValue(out ").Append(m.TypeName).AppendLine(" value)");
			_sb.AppendLine("\t{");
			_sb.Append("\t\tif (Tag == ").Append(m.Tag).Append(") { value = ").Append(m.Name).AppendLine("; return true; }");
			_sb.AppendLine("\t\tvalue = default;");
			_sb.AppendLine("\t\treturn false;");
			_sb.AppendLine("\t}");
		}
		_sb.AppendLine("}");
	}

	void EmitRefUnion(UnionDef u, bool allTables)
	{
		_sb.AppendLine();
		_sb.AppendLine("[Union]");
		_sb.Append("public readonly ref struct ").Append(u.Name).AppendLine(" : IUnion");
		_sb.AppendLine("{");
		_sb.AppendLine("\treadonly Span<byte> _buf;");
		_sb.AppendLine("\treadonly int _pos;");
		_sb.AppendLine("\tpublic readonly byte Tag;");
		_sb.Append("\tpublic ").Append(u.Name).AppendLine("(Span<byte> buffer, int position, byte tag) { _buf = buffer; _pos = position; Tag = tag; }");
		if (allTables)
			foreach (var m in u.Members)
				_sb.Append("\tpublic ").Append(u.Name).Append('(').Append(m.TypeName).Append(" value) { _buf = value.Buffer; _pos = value.BufferPos; Tag = ").Append(m.Tag).AppendLine("; }");
		_sb.Append("\tpublic object? Value => throw new NotImplementedException(\"Boxing not supported").Append(allTables ? ". Use TryGetAs." : ".").AppendLine("\");");
		_sb.AppendLine("\tpublic bool HasValue => Tag != 0 && _pos > 0;");
		if (allTables)
			foreach (var m in u.Members)
			{
				_sb.AppendLine();
				_sb.Append("\tpublic bool TryGetAs").Append(m.Name).Append("(out ").Append(m.TypeName).AppendLine(" value)");
				_sb.AppendLine("\t{");
				_sb.Append("\t\tif (Tag != ").Append(m.Tag).AppendLine(") { value = default; return false; }");
				_sb.Append("\t\tvalue = new ").Append(m.TypeName).AppendLine("(_buf, _pos);");
				_sb.AppendLine("\t\treturn true;");
				_sb.AppendLine("\t}");
			}
		_sb.AppendLine("}");
	}

	void EmitTable(TableDef t)
	{
		_sb.AppendLine();
		_sb.Append("public readonly ref partial struct ").AppendLine(t.Name);
		_sb.AppendLine("{");
		_sb.AppendLine("\treadonly Span<byte> _buf;");
		_sb.AppendLine("\treadonly int _pos;");

		_sb.Append("\tpublic const int SlotCount = ").Append(t.SlotCount).AppendLine(";");
		_sb.Append("\tpublic const int InlineSize = ").Append(t.InlineSize).AppendLine(";");
		_sb.Append("\tpublic const int InlineAlign = ").Append(t.InlineAlign).AppendLine(";");

		int effectiveAlign = t.InlineAlign < 4 ? 4 : t.InlineAlign;
		int maxSize = 2 * effectiveAlign + 2 * t.SlotCount + t.InlineSize + 10;
		_sb.Append("\tpublic const int TableMaxSize = ").Append(maxSize).AppendLine(";");
		_sb.AppendLine("\tpublic int GetSize() { int vt = _pos - FlatBufferReader.ReadUnaligned<int>(_buf, _pos); return FlatBufferReader.ReadUnaligned<ushort>(_buf, vt) + FlatBufferReader.ReadUnaligned<ushort>(_buf, vt + 2); }");
		EmitGetMaxSize(t);

		_sb.Append("\tpublic ").Append(t.Name).AppendLine("(Span<byte> buffer, int position) { _buf = buffer; _pos = position; }");

		EmitReserveConstructor(t);
		EmitBuildConstructor(t);

		_sb.Append("\tpublic static ").Append(t.Name).Append(" GetRootAs(Span<byte> buffer) => new ").Append(t.Name).AppendLine("(buffer, FlatBufferReader.GetRootOffset(buffer));");
		_sb.AppendLine("\tpublic Span<byte> Buffer => _buf;");
		_sb.AppendLine("\tpublic int BufferPos => _pos;");
		_sb.AppendLine("\tpublic bool IsValid => _pos > 0;");
		_sb.Append("\tpublic Offset<").Append(t.Name).Append("> AsOffset => new Offset<").Append(t.Name).AppendLine(">(_pos);");

		foreach (var f in t.Fields)
		{
			if (f.Deprecated)
				continue;
			EmitTableField(f);
		}

		_sb.AppendLine("\t[System.Diagnostics.CodeAnalysis.UnscopedRef]");
		_sb.AppendLine("\tpublic void MarkAsRoot(ref FlatBufferBuilder builder) => builder.MarkRoot(_pos);");

		_sb.AppendLine("}");

		EmitTableVector(t);
	}

	void EmitGetMaxSize(TableDef t)
	{
		var refFields = new List<(string paramName, string? sizeExpr)>();
		foreach (var f in t.Fields)
		{
			if (f.Deprecated)
				continue;
			string pname = ToCamelCase(f.Name);
			if (f.Type.IsString)
			{
				refFields.Add((pname + "ByteCount", "FlatBufferBuilder.StringMaxSize(" + pname + "ByteCount)"));
			}
			else if (f.Type.IsVector)
			{
				var elt = f.Type.ElementBase;
				if (elt.IsScalar())
				{
					refFields.Add((pname + "Count", "FlatBufferBuilder.VectorMaxSize<" + elt.ToCSharpKeyword() + ">(" + pname + "Count)"));
				}
				else if (elt == SchemaBaseType.String || elt == SchemaBaseType.Union)
				{
					refFields.Add((pname + "Count", "FlatBufferBuilder.VectorOfOffsetsMaxSize(" + pname + "Count)"));
				}
				else if (elt == SchemaBaseType.Obj && f.Type.ReferencedName != null)
				{
					if (_schema.ByName.TryGetValue(f.Type.ReferencedName, out var def))
					{
						if (def is StructDef)
							refFields.Add((pname + "Count", "FlatBufferBuilder.VectorMaxSize<" + f.Type.ReferencedName + ">(" + pname + "Count)"));
						else if (def is EnumDef ed)
							refFields.Add((pname + "Count", "FlatBufferBuilder.VectorMaxSize<" + ed.Underlying.ToCSharpKeyword() + ">(" + pname + "Count)"));
						else
						{
							refFields.Add((pname + "Count", null));
							refFields.Add((pname + "MaxSizeEach", "FlatBufferBuilder.VectorOfOffsetsMaxSize(" + pname + "Count) + " + pname + "Count * " + pname + "MaxSizeEach"));
						}
					}
				}
			}
		}

		_sb.Append("\tpublic static int GetMaxSize(");
		for (int i = 0; i < refFields.Count; i++)
		{
			if (i > 0)
				_sb.Append(", ");
			_sb.Append("int ").Append(refFields[i].paramName).Append(" = 0");
		}
		_sb.Append(") => TableMaxSize");
		foreach (var (_, sizeExpr) in refFields)
			if (sizeExpr != null)
				_sb.Append(" + ").Append(sizeExpr);
		_sb.AppendLine(";");
	}

	void EmitReserveConstructor(TableDef t)
	{
		_sb.Append("\tpublic static ").Append(t.Name).AppendLine(" Create(ref FlatBufferBuilder builder)");
		_sb.AppendLine("\t{");
		_sb.Append("\t\tint __pos = builder.StartTable(").Append(t.SlotCount).Append(", ").Append(t.InlineSize).Append(", ").Append(t.InlineAlign).AppendLine(");");
		_sb.AppendLine("\t\tvar __buf = builder.Buffer;");
		foreach (var f in t.Fields)
		{
			if (f.Deprecated)
				continue;
			EmitFieldAssign(f, forced: true);
		}
		_sb.AppendLine("\t\tbuilder.MarkRoot(__pos);");
		_sb.Append("\t\treturn new ").Append(t.Name).AppendLine("(__buf, __pos);");
		_sb.AppendLine("\t}");
	}

	void EmitFieldAssign(FieldDef f, bool forced)
	{
		int absInline = f.InlineOffset + 4;
		int vto = f.VTableOffset;
		string pname = ToCamelCase(f.Name);
		if (f.Type.IsUnion)
		{
			if (forced)
			{
				_sb.Append("\t\tVtable.WriteForced<byte>(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).AppendLine(", 0);");
			}
			else
			{
				int dataVto = vto + 2;
				int dataAbsInline = f.UnionDataInlineOffset + 4;
				_sb.Append("\t\tVtable.Write<byte>(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", (byte)").Append(pname).Append("Type, 0);");
				_sb.AppendLine();
				_sb.Append("\t\tif (").Append(pname).Append(" != 0) Vtable.WriteOffset(__buf, __pos, ").Append(dataVto).Append(", ").Append(dataAbsInline).Append(", ").Append(pname).AppendLine(");");
			}
			return;
		}
		if (f.Type.Base.IsScalar())
		{
			string cs = ScalarCSharpType(f.Type, out string defLit);
			string schemaDefault = !string.IsNullOrEmpty(f.DefaultValue) ? FormatDefault(f.Type, f.DefaultValue!) : defLit;
			if (forced)
				_sb.Append("\t\tVtable.WriteForced<").Append(cs).Append(">(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", ").Append(schemaDefault).AppendLine(");");
			else
				_sb.Append("\t\tVtable.Write<").Append(cs).Append(">(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", ").Append(pname).Append(", ").Append(schemaDefault).AppendLine(");");
			return;
		}
		if (f.Type.IsString || f.Type.IsVector)
		{
			if (!forced)
			{
				if (f.Required)
					_sb.Append("\t\tVtable.WriteOffset(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", ").Append(pname).AppendLine(");");
				else
					_sb.Append("\t\tif (").Append(pname).Append(" != 0) Vtable.WriteOffset(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", ").Append(pname).AppendLine(");");
			}
			return;
		}
		if (f.Type.IsObject && f.Type.ReferencedName != null && _schema.ByName.TryGetValue(f.Type.ReferencedName, out var def))
		{
			if (def is TableDef)
			{
				if (!forced)
				{
					if (f.Required)
						_sb.Append("\t\tVtable.WriteOffset(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", ").Append(pname).AppendLine(");");
					else
						_sb.Append("\t\tif (").Append(pname).Append(" != 0) Vtable.WriteOffset(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", ").Append(pname).AppendLine(");");
				}
				return;
			}
			if (def is StructDef)
			{
				if (forced)
					_sb.Append("\t\t{ var __v = default(").Append(f.Type.ReferencedName).Append("); Vtable.WriteForced<").Append(f.Type.ReferencedName).Append(">(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).AppendLine(", in __v); }");
				else
					_sb.Append("\t\t{ var __v = ").Append(pname).Append("; Vtable.WriteForced<").Append(f.Type.ReferencedName).Append(">(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).AppendLine(", in __v); }");
				return;
			}
			if (def is EnumDef ed)
			{
				string under = ed.Underlying.ToCSharpKeyword();
				string defValue = !string.IsNullOrEmpty(f.DefaultValue)
					? FormatEnumDefault(ed, f.DefaultValue!)
					: (ed.Underlying == SchemaBaseType.Long || ed.Underlying == SchemaBaseType.ULong ? "0L" : "0");
				if (forced)
					_sb.Append("\t\tVtable.WriteForced<").Append(under).Append(">(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", ").Append(defValue).AppendLine(");");
				else
					_sb.Append("\t\tVtable.Write<").Append(under).Append(">(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).Append(", (").Append(under).Append(')').Append(pname).Append(", ").Append(defValue).AppendLine(");");
				return;
			}
		}
		else if (f.Type.IsObject && f.Type.ReferencedName != null)
		{
			if (forced)
				_sb.Append("\t\t{ var __v = default(").Append(f.Type.ReferencedName).Append("); Vtable.WriteForced<").Append(f.Type.ReferencedName).Append(">(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).AppendLine(", in __v); }");
			else
				_sb.Append("\t\t{ var __v = ").Append(pname).Append("; Vtable.WriteForced<").Append(f.Type.ReferencedName).Append(">(__buf, __pos, ").Append(vto).Append(", ").Append(absInline).AppendLine(", in __v); }");
		}
	}

	void EmitBuildConstructor(TableDef t)
	{
		_sb.Append("\tpublic static ").Append(t.Name).Append(" Create(ref FlatBufferBuilder builder");
		foreach (var f in t.Fields)
		{
			if (f.Deprecated)
				continue;
			if (f.Type.IsUnion)
			{
				_sb.Append(", ").Append(f.Type.ReferencedName).Append("Kind ").Append(ToCamelCase(f.Name)).Append("Type = default");
				_sb.Append(", int ").Append(ToCamelCase(f.Name)).Append(" = 0");
				continue;
			}
			_sb.Append(", ").Append(BuildParamType(f)).Append(' ').Append(ToCamelCase(f.Name)).Append(" = ").Append(BuildParamDefault(f));
		}
		_sb.AppendLine(")");
		_sb.AppendLine("\t{");
		_sb.Append("\t\tint __pos = builder.StartTable(").Append(t.SlotCount).Append(", ").Append(t.InlineSize).Append(", ").Append(t.InlineAlign).AppendLine(");");
		_sb.AppendLine("\t\tvar __buf = builder.Buffer;");
		foreach (var f in t.Fields)
		{
			if (f.Deprecated)
				continue;
			EmitFieldAssign(f, forced: false);
		}
		_sb.AppendLine("\t\tbuilder.MarkRoot(__pos);");
		_sb.Append("\t\treturn new ").Append(t.Name).AppendLine("(__buf, __pos);");
		_sb.AppendLine("\t}");
	}

	string BuildParamType(FieldDef f)
	{
		if (f.Type.Base.IsScalar())
			return ScalarCSharpType(f.Type, out _);
		if (f.Type.IsString)
			return "StringOffset";
		if (f.Type.IsVector)
			return "VectorOffset";
		if (f.Type.IsObject && f.Type.ReferencedName != null && _schema.ByName.TryGetValue(f.Type.ReferencedName, out var def))
		{
			if (def is TableDef)
				return "Offset<" + f.Type.ReferencedName + ">";
			if (def is StructDef)
				return f.Type.ReferencedName;
			if (def is EnumDef)
				return f.Type.ReferencedName;
		}
		return f.Type.ReferencedName ?? "int";
	}

	string BuildParamDefault(FieldDef f)
	{
		if (f.Type.Base.IsScalar())
		{
			ScalarCSharpType(f.Type, out string defLit);
			return !string.IsNullOrEmpty(f.DefaultValue) ? FormatDefault(f.Type, f.DefaultValue!) : defLit;
		}
		if (f.Type.IsString || f.Type.IsVector)
			return "default";
		if (f.Type.IsObject && f.Type.ReferencedName != null && _schema.ByName.TryGetValue(f.Type.ReferencedName, out var def))
		{
			if (def is TableDef)
				return "default";
			if (def is StructDef)
				return "default";
			if (def is EnumDef ed2)
			{
				if (!string.IsNullOrEmpty(f.DefaultValue))
				{
					if (f.DefaultValue!.Length > 0 && (char.IsDigit(f.DefaultValue[0]) || f.DefaultValue[0] == '-'))
						return "(" + ed2.Name + ")" + f.DefaultValue;
					return ed2.Name + "." + f.DefaultValue;
				}
				return "default";
			}
		}
		return f.Type.IsObject && f.Type.ReferencedName != null ? "default" : "0";
	}



	void EmitTableField(FieldDef f)
	{
		string propName = ToPascalCase(f.Name);
		int vto = f.VTableOffset;
		int absInline = f.InlineOffset + 4;

		if (f.Type.Base.IsScalar())
		{
			string cs = ScalarCSharpType(f.Type, out string defaultLiteral);
			string def = !string.IsNullOrEmpty(f.DefaultValue) ? FormatDefault(f.Type, f.DefaultValue!) : defaultLiteral;
			EmitScalarProperty(cs, cs, propName, vto, absInline, def, castUnderlying: null);
			return;
		}
		if (f.Type.IsString)
		{
			_sb.Append("\tpublic FlatString ").Append(propName).Append(" => new FlatString(_buf, Vtable.ReadIndirect(_buf, _pos, ").Append(vto).AppendLine("));");
			return;
		}
		if (f.Type.IsObject)
		{
			var name = f.Type.ReferencedName!;
			if (_schema.ByName.TryGetValue(name, out var def))
			{
				if (def is TableDef)
				{
					_sb.Append("\tpublic ").Append(name).Append(' ').Append(propName).Append(" => new ").Append(name).Append("(_buf, Vtable.ReadIndirect(_buf, _pos, ").Append(vto).AppendLine("));");
					return;
				}
				if (def is StructDef)
				{
					EmitStructRefProperty(name, propName, vto, absInline);
					return;
				}
				if (def is EnumDef ed)
				{
					string underlying = ed.Underlying.ToCSharpKeyword();
					string defLit = !string.IsNullOrEmpty(f.DefaultValue)
						? FormatEnumDefault(ed, f.DefaultValue!)
						: (ed.Underlying == SchemaBaseType.Long || ed.Underlying == SchemaBaseType.ULong ? "0L" : "0");
					EmitScalarProperty(name, underlying, propName, vto, absInline, defLit, castUnderlying: underlying);
					return;
				}
			}
			else
			{
				EmitStructRefProperty(name, propName, vto, absInline);
			}
			return;
		}
		if (f.Type.IsVector)
		{
			EmitVectorReader(f, propName, vto);
			return;
		}
		if (f.Type.IsUnion)
		{
			var unionName = f.Type.ReferencedName!;
			int typeVto = vto;
			int dataVto = vto + 2;
			int typeAbsInline = f.InlineOffset + 4;
			EmitScalarProperty(unionName + "Kind", "byte", propName + "Type", typeVto, typeAbsInline, "0", castUnderlying: "byte");
			if (_refUnions.Contains(unionName))
			{
				_sb.Append("\tpublic ").Append(unionName).Append(' ').Append(propName)
					.Append(" => new ").Append(unionName).Append("(_buf, Vtable.ReadIndirect(_buf, _pos, ").Append(dataVto)
					.Append("), Vtable.Read<byte>(_buf, _pos, ").Append(typeVto).AppendLine(", 0));");
			}
			else
			{
				int dataAbsInline = f.UnionDataInlineOffset + 4;
				EmitStructRefProperty(unionName, propName, dataVto, dataAbsInline);
			}
		}
	}

	void EmitStructRefProperty(string typeName, string propName, int vto, int absInline)
	{
		_sb.Append("\tpublic ").Append(typeName).Append(' ').Append(propName)
			.Append(" { get => Vtable.StructOffset(_buf, _pos, ").Append(vto).Append(") is var o && o == 0 ? default : FlatBufferReader.ReadUnaligned<").Append(typeName).Append(">(_buf, o);")
			.Append(" set => Vtable.WriteForced<").Append(typeName).Append(">(_buf, _pos, ").Append(vto).Append(", ").Append(absInline).AppendLine(", in value); }");
	}

	void EmitScalarProperty(string publicType, string underlying, string propName, int vto, int absInline, string def, string? castUnderlying)
	{
		_sb.Append("\tpublic ").Append(publicType).Append(' ').Append(propName).Append(" { get => ");
		if (castUnderlying != null)
			_sb.Append('(').Append(publicType).Append(")(");
		_sb.Append("Vtable.Read<").Append(underlying).Append(">(_buf, _pos, ").Append(vto).Append(", ").Append(def).Append(')');
		if (castUnderlying != null)
			_sb.Append(')');
		_sb.Append("; set => Vtable.Write<").Append(underlying).Append(">(_buf, _pos, ").Append(vto).Append(", ").Append(absInline).Append(", ");
		if (castUnderlying != null)
			_sb.Append('(').Append(underlying).Append(')');
		_sb.Append("value, ").Append(def).AppendLine("); }");
	}

	void EmitVectorReader(FieldDef f, string propName, int vto)
	{
		var elt = f.Type.ElementBase;
		if (elt.IsScalar())
		{
			string cs = elt.ToCSharpKeyword();
			_sb.Append("\tpublic FlatVector<").Append(cs).Append("> ").Append(propName).Append(" => new FlatVector<").Append(cs).Append(">(_buf, Vtable.ReadIndirect(_buf, _pos, ").Append(vto).AppendLine("));");
			if (elt == SchemaBaseType.UByte && !string.IsNullOrEmpty(f.NestedFlatBufferType) && IsValidCSharpIdentifier(f.NestedFlatBufferType!))
				_sb.Append("\tpublic ").Append(f.NestedFlatBufferType).Append(' ').Append(propName).Append("Nested => ").Append(f.NestedFlatBufferType).Append(".GetRootAs(").Append(propName).AppendLine(".AsSpan);");
			return;
		}
		if (elt == SchemaBaseType.String)
		{
			_sb.Append("\tpublic FlatStringVector ").Append(propName).Append(" => new FlatStringVector(_buf, Vtable.ReadIndirect(_buf, _pos, ").Append(vto).AppendLine("));");
			return;
		}
		if (elt == SchemaBaseType.Obj && f.Type.ReferencedName != null)
		{
			var name = f.Type.ReferencedName;
			if (_schema.ByName.TryGetValue(name, out var def))
			{
				if (def is StructDef)
				{
					_sb.Append("\tpublic FlatVector<").Append(name).Append("> ").Append(propName).Append(" => new FlatVector<").Append(name).Append(">(_buf, Vtable.ReadIndirect(_buf, _pos, ").Append(vto).AppendLine("));");
					return;
				}
				if (def is TableDef)
				{
					_sb.Append("\tpublic ").Append(name).Append("Vector ").Append(propName).Append(" => new ").Append(name).Append("Vector(_buf, Vtable.ReadIndirect(_buf, _pos, ").Append(vto).AppendLine("));");
					return;
				}
				if (def is EnumDef ed)
				{
					string cs = ed.Underlying.ToCSharpKeyword();
					_sb.Append("\tpublic FlatVector<").Append(cs).Append("> ").Append(propName).Append(" => new FlatVector<").Append(cs).Append(">(_buf, Vtable.ReadIndirect(_buf, _pos, ").Append(vto).AppendLine("));");
					return;
				}
			}
		}
	}

	void EmitTableVector(TableDef t)
	{
		_sb.AppendLine();
		_sb.Append("public readonly ref struct ").Append(t.Name).AppendLine("Vector");
		_sb.AppendLine("{");
		_sb.AppendLine("\treadonly Span<byte> _buf;");
		_sb.AppendLine("\treadonly int _pos;");
		_sb.Append("\tpublic ").Append(t.Name).AppendLine("Vector(Span<byte> buffer, int position) { _buf = buffer; _pos = position; }");
		_sb.AppendLine("\tpublic bool IsValid => _pos > 0;");
		_sb.AppendLine("\tpublic int Length => _pos <= 0 ? 0 : (int)FlatBufferReader.ReadUnaligned<uint>(_buf, _pos);");
		_sb.Append("\tpublic ").Append(t.Name).AppendLine(" this[int index]");
		_sb.AppendLine("\t{");
		_sb.AppendLine("\t\tget");
		_sb.AppendLine("\t\t{");
		_sb.AppendLine("\t\t\tint elt = _pos + 4 + index * 4;");
		_sb.Append("\t\t\treturn new ").Append(t.Name).AppendLine("(_buf, elt + (int)FlatBufferReader.ReadUnaligned<uint>(_buf, elt));");
		_sb.AppendLine("\t\t}");
		_sb.AppendLine("\t}");

		FieldDef? keyField = null;
		foreach (var f in t.Fields)
		{
			if (!f.Deprecated && f.IsKey)
			{
				keyField = f;
				break;
			}
		}

		if (keyField != null)
			EmitLookupByKey(t, keyField);

		_sb.AppendLine("}");
	}

	void EmitLookupByKey(TableDef t, FieldDef keyField)
	{
		string propName = ToPascalCase(keyField.Name);
		bool isString = keyField.Type.IsString;
		string keyType = isString ? "ReadOnlySpan<byte>" : ScalarCSharpType(keyField.Type, out _);

		_sb.AppendLine();
		_sb.Append("\tpublic ").Append(t.Name).Append(" LookupByKey(").Append(keyType).AppendLine(" key)");
		_sb.AppendLine("\t{");
		_sb.AppendLine("\t\tint lo = 0, hi = Length - 1;");
		_sb.AppendLine("\t\twhile (lo <= hi)");
		_sb.AppendLine("\t\t{");
		_sb.AppendLine("\t\t\tint mid = (lo + hi) >> 1;");
		_sb.AppendLine("\t\t\tvar entry = this[mid];");
		if (isString)
		{
			_sb.Append("\t\t\tint cmp = entry.").Append(propName).AppendLine(".AsBytes.SequenceCompareTo(key);");
			_sb.AppendLine("\t\t\tif (cmp == 0) return entry;");
			_sb.AppendLine("\t\t\tif (cmp < 0) lo = mid + 1; else hi = mid - 1;");
		}
		else
		{
			_sb.Append("\t\t\tvar k = entry.").Append(propName).AppendLine(";");
			_sb.AppendLine("\t\t\tif (k == key) return entry;");
			_sb.AppendLine("\t\t\tif (k < key) lo = mid + 1; else hi = mid - 1;");
		}
		_sb.AppendLine("\t\t}");
		_sb.AppendLine("\t\treturn default;");
		_sb.AppendLine("\t}");
	}

	static string ScalarCSharpType(TypeRef type, out string defaultLiteral)
	{
		defaultLiteral = "0";
		string cs = type.Base.ToCSharpKeyword();
		if (cs == "bool")
			defaultLiteral = "false";
		else if (cs == "float")
			defaultLiteral = "0f";
		else if (cs == "double")
			defaultLiteral = "0d";
		else if (cs == "long")
			defaultLiteral = "0L";
		else if (cs == "ulong")
			defaultLiteral = "0UL";
		return cs;
	}

	static string FormatDefault(TypeRef type, string raw)
	{
		if (type.Base == SchemaBaseType.Bool)
			return raw == "true" ? "true" : "false";
		if (type.Base == SchemaBaseType.Float)
		{
			if (raw == "inf" || raw == "infinity")
				return "float.PositiveInfinity";
			if (raw == "-inf" || raw == "-infinity")
				return "float.NegativeInfinity";
			if (raw == "nan")
				return "float.NaN";
			return raw + "f";
		}
		if (type.Base == SchemaBaseType.Double)
		{
			if (raw == "inf" || raw == "infinity")
				return "double.PositiveInfinity";
			if (raw == "-inf" || raw == "-infinity")
				return "double.NegativeInfinity";
			if (raw == "nan")
				return "double.NaN";
			return raw + "d";
		}
		if (type.Base == SchemaBaseType.Long)
			return raw + "L";
		if (type.Base == SchemaBaseType.ULong)
			return raw + "UL";
		return raw;
	}

	string ResolveTypeName(TypeRef type)
	{
		if (type.Base.IsScalar())
			return type.Base.ToCSharpKeyword();
		if (type.Base == SchemaBaseType.Obj && type.ReferencedName != null)
			return type.ReferencedName;
		return "object";
	}

	static string ToPascalCase(string s)
	{
		if (string.IsNullOrEmpty(s))
			return s;
		var sb = new StringBuilder(s.Length);
		bool upper = true;
		foreach (var c in s)
		{
			if (c == '_')
			{
				upper = true;
				continue;
			}
			sb.Append(upper ? char.ToUpperInvariant(c) : c);
			upper = false;
		}
		return sb.ToString();
	}

	static string ToCamelCase(string s)
	{
		string pascal = ToPascalCase(s);
		if (string.IsNullOrEmpty(pascal))
			return pascal;
		return char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);
	}

	static int AlignUp(int value, int alignment)
	{
		if (alignment <= 1)
			return value;
		return (value + alignment - 1) & ~(alignment - 1);
	}

	static string FormatEnumDefault(EnumDef ed, string raw)
	{
		string under = ed.Underlying.ToCSharpKeyword();
		if (raw.Length > 0 && (char.IsDigit(raw[0]) || raw[0] == '-'))
			return "(" + under + ")" + raw;
		return "(" + under + ")" + ed.Name + "." + raw;
	}

	static bool IsValidCSharpIdentifier(string s)
	{
		if (string.IsNullOrEmpty(s))
			return false;
		if (s[0] == '.' || s[s.Length - 1] == '.')
			return false;
		for (int i = 0; i < s.Length; i++)
		{
			char c = s[i];
			if (c == '.')
				continue;
			if (c == '_')
				continue;
			if (i == 0 || (i > 0 && s[i - 1] == '.'))
			{
				if (!char.IsLetter(c) && c != '_')
					return false;
			}
			else if (!char.IsLetterOrDigit(c))
				return false;
		}
		return true;
	}
}