using FlatBufferLite.SourceGen.IR;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using System.Threading;

namespace FlatBufferLite.SourceGen.Emit;

public sealed partial class CodeEmitter
{
	readonly Schema _schema;
	readonly CancellationToken _cancellationToken;
	readonly StringBuilder _sb = new();
	readonly HashSet<string> _refUnions = new();
	readonly HashSet<string> _autoPlainStructs = new();

	public CodeEmitter(Schema schema, CancellationToken cancellationToken = default) 
	{ 
		_schema = schema; 
		_cancellationToken = cancellationToken;
	}

	public string Emit()
	{
		_sb.Clear();
		_sb.AppendLine("// <auto-generated/> FlatBufferLite source generator");
		_sb.AppendLine("#nullable enable");
		_sb.AppendLine("using System;");
		_sb.AppendLine("using System.Collections.Generic;");
		_sb.AppendLine("using System.Runtime.CompilerServices;");
		_sb.AppendLine("using System.Runtime.InteropServices;");
		_sb.AppendLine("using FlatBufferLite;");

		var referencedNamespaces = new HashSet<string?>();
		foreach (var t in _schema.Tables)
			referencedNamespaces.Add(t.Namespace);
		foreach (var s in _schema.Structs)
			referencedNamespaces.Add(s.Namespace);
		foreach (var e in _schema.Enums)
			referencedNamespaces.Add(e.Namespace);
		foreach (var u in _schema.Unions)
			referencedNamespaces.Add(u.Namespace);
		foreach (var ns in referencedNamespaces)
			if (!string.IsNullOrEmpty(ns))
				_sb.Append("using ").Append(ns).AppendLine(";");

		int enumCount = _schema.LocalEnumCount;
		int structCount = _schema.LocalStructCount;
		int unionCount = _schema.LocalUnionCount;
		int tableCount = _schema.LocalTableCount;

		for (int i = 0; i < unionCount; i++)
		{
			_cancellationToken.ThrowIfCancellationRequested();
			PreclassifyUnion(_schema.Unions[i]);
		}

		var namespaces = new List<string?>();
		var nsSeen = new HashSet<string?>();
		void Track(string? ns)
		{
			if (nsSeen.Add(ns))
				namespaces.Add(ns);
		}
		for (int i = 0; i < enumCount; i++)
			Track(_schema.Enums[i].Namespace);
		for (int i = 0; i < structCount; i++)
			Track(_schema.Structs[i].Namespace);
		for (int i = 0; i < unionCount; i++)
			Track(_schema.Unions[i].Namespace);
		for (int i = 0; i < tableCount; i++)
			Track(_schema.Tables[i].Namespace);

		foreach (var ns in namespaces)
		{
			_cancellationToken.ThrowIfCancellationRequested();
			bool hasNs = !string.IsNullOrEmpty(ns);
			if (hasNs)
			{
				_sb.AppendLine();
				_sb.Append("namespace ").AppendLine(ns);
				_sb.AppendLine("{");
			}
			for (int i = 0; i < enumCount; i++)
				if (_schema.Enums[i].Namespace == ns)
					EmitEnum(_schema.Enums[i]);
			for (int i = 0; i < structCount; i++)
				if (_schema.Structs[i].Namespace == ns)
					EmitStruct(_schema.Structs[i]);
			for (int i = 0; i < unionCount; i++)
				if (_schema.Unions[i].Namespace == ns)
				{
					EmitUnion(_schema.Unions[i]);
					EmitPlainUnion(_schema.Unions[i]);
				}
			for (int i = 0; i < tableCount; i++)
				if (_schema.Tables[i].Namespace == ns)
					EmitTable(_schema.Tables[i]);
			if (hasNs)
				_sb.AppendLine("}");
		}
		return _sb.ToString();
	}

	void EmitEnum(EnumDef e)
	{
		_sb.AppendLine();
		if (e.IsBitFlags)
			_sb.AppendLine("[System.Flags]");
		_sb.Append("public enum ").Append(e.Name).Append(" : ").AppendLine(e.Underlying.ToCSharpKeyword());
		_sb.AppendLine("{");
		foreach (var v in e.Values)
		{
			long emitValue = e.IsBitFlags
				? (v.IsExplicit && v.Value == 0 ? 0 : 1L << (int)v.Value)
				: v.Value;
			_sb.Append('\t').Append(v.Name).Append(" = ").Append(emitValue.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
		}
		_sb.AppendLine("}");
	}

	void EmitStruct(StructDef s)
	{
		_sb.AppendLine();
		_sb.Append("[StructLayout(LayoutKind.Explicit, Size = ").Append(s.Size).AppendLine(")]");
		_sb.Append("public partial struct ").AppendLine(s.Name);
		_sb.AppendLine("{");
		foreach (var f in s.Fields)
		{
			string cs = ResolveTypeName(f.Type);
			_sb.Append("\t[FieldOffset(").Append(f.Offset).AppendLine(")]");
			_sb.Append("\tpublic ").Append(cs).Append(' ').Append(ToPascalCase(f.Name)).AppendLine(";");
		}
		_sb.AppendLine("}");
	}

	void EmitTable(TableDef t)
	{
		_sb.AppendLine();
		_sb.Append("public readonly ref partial struct ").Append(t.Name).AppendLine("Ref");
		_sb.AppendLine("{");
		_sb.AppendLine("\treadonly Span<byte> _buf;");
		_sb.AppendLine("\treadonly int _pos;");

		_sb.Append("\tpublic const int SlotCount = ").Append(t.SlotCount).AppendLine(";");
		_sb.Append("\tpublic const int InlineSize = ").Append(t.InlineSize).AppendLine(";");
		_sb.Append("\tpublic const int InlineAlign = ").Append(t.InlineAlign).AppendLine(";");

		EmitGetMaxSize(t);

		_sb.Append("\tpublic ").Append(t.Name).Append("Ref").AppendLine("(Span<byte> buffer, int position) { _buf = buffer; _pos = position; }");

		EmitReserveConstructor(t);
		EmitBuildConstructor(t);

		_sb.Append("\tpublic static ").Append(t.Name).Append("Ref").Append(" GetRootAs(Span<byte> buffer) => new ").Append(t.Name).Append("Ref").AppendLine("(buffer, FlatBufferReader.GetRootOffset(buffer));");
		_sb.AppendLine("\tpublic Span<byte> Buffer => _buf;");
		_sb.AppendLine("\tpublic int BufferPos => _pos;");
		_sb.AppendLine("\tpublic bool IsValid => _pos > 0;");
		_sb.Append("\tpublic Offset<").Append(t.Name).Append("Ref").Append("> AsOffset => new Offset<").Append(t.Name).Append("Ref").AppendLine(">(_pos);");

		foreach (var f in t.Fields)
		{
			if (f.Deprecated)
				continue;
			EmitTableField(f);
		}

		_sb.AppendLine("\t[System.Diagnostics.CodeAnalysis.UnscopedRef]");
		_sb.AppendLine("\tpublic void MarkAsRoot(ref FlatBufferBuilder builder) => builder.MarkRoot(_pos);");

		if (t.PlainStruct || _autoPlainStructs.Contains(t.Name))
			EmitPlainTableMethods(t);

		_sb.AppendLine("}");

		EmitTableVector(t);
		if (t.PlainStruct || _autoPlainStructs.Contains(t.Name))
			EmitPlainStruct(t);
	}
}
