using FlatBufferLite.SourceGen.IR;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace FlatBufferLite.SourceGen.Emit;

public sealed partial class CodeEmitter
{
	readonly Schema _schema;
	readonly CancellationToken _cancellationToken;
	readonly IndentedWriter _w = new();
	readonly HashSet<string> _refUnions = new();
	readonly HashSet<string> _autoPlainStructs = new();

	public CodeEmitter(Schema schema, CancellationToken cancellationToken = default)
	{
		_schema = schema;
		_cancellationToken = cancellationToken;
	}

	public string Emit()
	{
		_w.Clear();
		_w.AppendLine("// <auto-generated/> FlatBufferLite source generator");
		_w.AppendLine("#nullable enable");
		_w.AppendLine("using System;");
		_w.AppendLine("using System.Collections.Generic;");
		_w.AppendLine("using System.Runtime.CompilerServices;");
		_w.AppendLine("using System.Runtime.InteropServices;");
		_w.AppendLine("using FlatBufferLite;");

		var referencedNamespaces = new HashSet<string>();
		void TrackReferencedNamespace(string? ns)
		{
			if (ns is { Length: > 0 } namespaceName)
				referencedNamespaces.Add(namespaceName);
		}
		foreach (var t in _schema.Tables)
			TrackReferencedNamespace(t.Namespace);
		foreach (var s in _schema.Structs)
			TrackReferencedNamespace(s.Namespace);
		foreach (var e in _schema.Enums)
			TrackReferencedNamespace(e.Namespace);
		foreach (var u in _schema.Unions)
			TrackReferencedNamespace(u.Namespace);
		foreach (var ns in referencedNamespaces)
			_w.Append("using ").Append(ns).AppendLine(";");

		int enumCount = _schema.LocalEnumCount;
		int structCount = _schema.LocalStructCount;
		int unionCount = _schema.LocalUnionCount;
		int tableCount = _schema.LocalTableCount;

		for (int i = 0; i < unionCount; i++)
		{
			_cancellationToken.ThrowIfCancellationRequested();
			PreclassifyUnion(_schema.Unions[i]);
		}

		var namespaces = new List<string?>();
		var nsSeen = new HashSet<string?>();
		void Track(string? ns)
		{
			if (nsSeen.Add(ns))
				namespaces.Add(ns);
		}
		for (int i = 0; i < enumCount; i++)
			Track(_schema.Enums[i].Namespace);
		for (int i = 0; i < structCount; i++)
			Track(_schema.Structs[i].Namespace);
		for (int i = 0; i < unionCount; i++)
			Track(_schema.Unions[i].Namespace);
		for (int i = 0; i < tableCount; i++)
			Track(_schema.Tables[i].Namespace);

		foreach (var ns in namespaces)
		{
			_cancellationToken.ThrowIfCancellationRequested();
			string? namespaceName = ns is { Length: > 0 } ? ns : null;
			if (namespaceName != null)
			{
				_w.AppendLine();
				_w.Append("namespace ").AppendLine(namespaceName);
				_w.AppendLine("{");
			}
			for (int i = 0; i < enumCount; i++)
				if (_schema.Enums[i].Namespace == ns)
					EmitEnum(_schema.Enums[i]);
			for (int i = 0; i < structCount; i++)
				if (_schema.Structs[i].Namespace == ns)
					EmitStruct(_schema.Structs[i]);
			for (int i = 0; i < unionCount; i++)
				if (_schema.Unions[i].Namespace == ns)
				{
					EmitUnion(_schema.Unions[i]);
					EmitPlainUnion(_schema.Unions[i]);
				}
			for (int i = 0; i < tableCount; i++)
				if (_schema.Tables[i].Namespace == ns)
					EmitTable(_schema.Tables[i]);
			if (namespaceName != null)
				_w.AppendLine("}");
		}
		return _w.ToString();
	}

	void EmitEnum(EnumDef e)
	{
		_w.AppendLine();
		if (e.IsBitFlags)
			_w.AppendLine("[System.Flags]");
		_w.OpenBlock("public enum " + e.Name + " : " + e.Underlying.ToCSharpKeyword());
		foreach (var v in e.Values)
		{
			long emitValue = e.IsBitFlags
			? (v.IsExplicit && v.Value == 0 ? 0 : 1L << (int)v.Value)
			: v.Value;
			_w.Append(v.Name).Append(" = ").Append(emitValue.ToString(CultureInfo.InvariantCulture)).AppendLine(",");
		}
		_w.CloseBlock();
	}

	void EmitStruct(StructDef s)
	{
		_w.AppendLine();
		EmitStructLayoutExplicit(s.Size);
		_w.AppendLine("public partial struct " + s.Name);
		_w.OpenBlock();
		foreach (var f in s.Fields)
		{
			string cs = ResolveTypeName(f.Type);
			EmitFieldOffsetField(f.Offset, cs, ToPascalCase(f.Name));
		}
		_w.CloseBlock();
	}

	void EmitTable(TableDef t)
	{
		_w.AppendLine();
		_w.AppendLine("public readonly ref partial struct " + t.Name + "Ref");
		_w.OpenBlock();
		EmitReadonlyField("Span<byte>", "_buf");
		EmitReadonlyField("int", "_pos");

		EmitPublicConst("int", "SlotCount", t.SlotCount.ToString(CultureInfo.InvariantCulture));
		EmitPublicConst("int", "InlineSize", t.InlineSize.ToString(CultureInfo.InvariantCulture));
		EmitPublicConst("int", "InlineAlign", t.InlineAlign.ToString(CultureInfo.InvariantCulture));

		EmitGetMaxSize(t);

		_w.Append("public ").Append(t.Name).Append("Ref").AppendLine("(Span<byte> buffer, int position) { _buf = buffer; _pos = position; }");

		EmitReserveConstructor(t);
		EmitBuildConstructor(t);

		_w.Append("public static ").Append(t.Name).Append("Ref").Append(" GetRootAs(Span<byte> buffer) => new ").Append(t.Name).Append("Ref").AppendLine("(buffer, FlatBufferReader.GetRootOffset(buffer));");
		_w.AppendLine("public Span<byte> Buffer => _buf;");
		_w.AppendLine("public int BufferPos => _pos;");
		_w.AppendLine("public bool IsValid => _pos > 0;");
		_w.Append("public Offset<").Append(t.Name).Append("Ref>").Append(" AsOffset => new Offset<").Append(t.Name).Append("Ref>").AppendLine("(_pos);");

		foreach (var f in t.Fields)
		{
			if (f.Deprecated)
				continue;
			EmitTableField(f);
		}

		_w.AppendLine("[System.Diagnostics.CodeAnalysis.UnscopedRef]");
		_w.AppendLine("public void MarkAsRoot(ref FlatBufferBuilder builder) => builder.MarkRoot(_pos);");

		if (t.PlainStruct || _autoPlainStructs.Contains(t.Name))
			EmitPlainTableMethods(t);

		_w.CloseBlock();

		EmitTableVector(t);
		if (t.PlainStruct || _autoPlainStructs.Contains(t.Name))
			EmitPlainStruct(t);
	}
}
