attribute "plain_struct";
attribute "CustomCollection";

namespace FlatBufferLite.PlainStructs;

enum Quality : ubyte {
	Low = 0,
	High = 1,
}

struct Vec2 {
	x: float;
	y: float;
}

table Item (plain_struct) {
	id: int;
	name: string;
	pos: Vec2;
	quality: Quality = High;
}

table Bag (plain_struct) {
	title: string;
	scores: [int];
	names: [string];
	items: [Item];
	qualities: [Quality];
}

table CollectionBag (plain_struct) {
	title: string (CustomCollection);
	scores: [int] (CustomCollection);
	names: [string] (CustomCollection);
	items: [Item] (CustomCollection);
	qualities: [Quality] (CustomCollection);
}

table PlainCircle (plain_struct) {
	radius: float;
	label: string;
}

table PlainRectangle (plain_struct) {
	width: float;
	height: float;
}

union PlainShape {
	PlainCircle,
	PlainRectangle,
}

table ShapeHolder (plain_struct) {
	name: string;
	shape: PlainShape;
}

table RefShapeHolder {
	shape: PlainShape;
}

table Label {
	name: string;
}

table Shelf {
	bag: Bag;
	label: Label;
}

root_type Bag;
