<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlatBufferLite\FlatBufferLite.csproj" />
    <ProjectReference Include="..\FlatBufferLite.SourceGen\FlatBufferLite.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Schemas\**\*.fbs" />
  </ItemGroup>

</Project>
